import { lazy } from 'react';
import type { ToolConfig, ToolCategory } from '../types';

export const TOOL_CATEGORIES: Record<ToolCategory, { label: string; description: string }> = {
  organize: { label: 'Organize', description: 'Merge, split, and reorder your PDF pages' },
  convert: { label: 'Convert', description: 'Convert between PDF and image formats' },
  edit: { label: 'Edit', description: 'Modify content, add watermarks, and annotate' },
  security: { label: 'Security', description: 'Protect, unlock, and sign your documents' },
};

export const toolRegistry: ToolConfig[] = [
  {
    id: 'merge',
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into one document',
    route: '/merge-pdf',
    icon: '📎',
    color: '#6366f1',
    category: 'organize',
    component: lazy(() => import('../tools/MergePdf/MergePdf')),
    acceptMultiple: true,
  },
  {
    id: 'split',
    name: 'Split PDF',
    description: 'Split a PDF into multiple separate documents',
    route: '/split-pdf',
    icon: '✂️',
    color: '#8b5cf6',
    category: 'organize',
    component: lazy(() => import('../tools/SplitPdf/SplitPdf')),
  },
  {
    id: 'compress',
    name: 'Compress PDF',
    description: 'Reduce PDF file size while maintaining quality',
    route: '/compress-pdf',
    icon: '🗜️',
    color: '#22c55e',
    category: 'organize',
    component: lazy(() => import('../tools/CompressPdf/CompressPdf')),
  },
  {
    id: 'rotate',
    name: 'Rotate PDF',
    description: 'Rotate individual or all pages in your PDF',
    route: '/rotate-pdf',
    icon: '🔄',
    color: '#f59e0b',
    category: 'organize',
    component: lazy(() => import('../tools/RotatePdf/RotatePdf')),
  },
  {
    id: 'remove-pages',
    name: 'Remove Pages',
    description: 'Delete specific pages from your PDF document',
    route: '/remove-pages',
    icon: '🗑️',
    color: '#ef4444',
    category: 'organize',
    component: lazy(() => import('../tools/RemovePages/RemovePages')),
  },
  {
    id: 'extract-pages',
    name: 'Extract Pages',
    description: 'Extract selected pages into a new PDF file',
    route: '/extract-pages',
    icon: '📄',
    color: '#06b6d4',
    category: 'organize',
    component: lazy(() => import('../tools/ExtractPages/ExtractPages')),
  },
  {
    id: 'sort-pages',
    name: 'Sort Pages',
    description: 'Rearrange pages in your PDF by drag and drop',
    route: '/sort-pages',
    icon: '🔀',
    color: '#14b8a6',
    category: 'organize',
    component: lazy(() => import('../tools/SortPages/SortPages')),
  },
  {
    id: 'images-to-pdf',
    name: 'Images to PDF',
    description: 'Convert JPG, PNG, or WebP images to a PDF',
    route: '/images-to-pdf',
    icon: '🖼️',
    color: '#a855f7',
    category: 'convert',
    component: lazy(() => import('../tools/ImagesToPdf/ImagesToPdf')),
    acceptMultiple: true,
    acceptTypes: ['image/jpeg', 'image/png', 'image/webp'],
  },
  {
    id: 'pdf-to-images',
    name: 'PDF to Images',
    description: 'Convert each PDF page to a high-quality image',
    route: '/pdf-to-images',
    icon: '📸',
    color: '#ec4899',
    category: 'convert',
    component: lazy(() => import('../tools/PdfToImages/PdfToImages')),
  },
  {
    id: 'add-watermark',
    name: 'Add Watermark',
    description: 'Add text or image watermarks to your PDF',
    route: '/add-watermark',
    icon: '💧',
    color: '#0ea5e9',
    category: 'edit',
    component: lazy(() => import('../tools/AddWatermark/AddWatermark')),
  },
  {
    id: 'add-page-numbers',
    name: 'Add Page Numbers',
    description: 'Add page numbers to your PDF document',
    route: '/add-page-numbers',
    icon: '🔢',
    color: '#64748b',
    category: 'edit',
    component: lazy(() => import('../tools/AddPageNumbers/AddPageNumbers')),
  },
  {
    id: 'crop-pdf',
    name: 'Crop PDF',
    description: 'Crop and trim margins of PDF pages',
    route: '/crop-pdf',
    icon: '✂️',
    color: '#f97316',
    category: 'edit',
    component: lazy(() => import('../tools/CropPdf/CropPdf')),
  },
  {
    id: 'flatten-pdf',
    name: 'Flatten PDF',
    description: 'Flatten form fields and annotations in PDF',
    route: '/flatten-pdf',
    icon: '📋',
    color: '#84cc16',
    category: 'edit',
    component: lazy(() => import('../tools/FlattenPdf/FlattenPdf')),
  },
  {
    id: 'extract-images',
    name: 'Extract Images',
    description: 'Extract all images embedded in a PDF',
    route: '/extract-images',
    icon: '🖼️',
    color: '#d946ef',
    category: 'convert',
    component: lazy(() => import('../tools/ExtractImages/ExtractImages')),
  },
  {
    id: 'compare-pdfs',
    name: 'Compare PDFs',
    description: 'Compare two PDF files side by side',
    route: '/compare-pdfs',
    icon: '🔍',
    color: '#0891b2',
    category: 'edit',
    component: lazy(() => import('../tools/ComparePdfs/ComparePdfs')),
    acceptMultiple: true,
  },
  {
    id: 'sign-pdf',
    name: 'Sign PDF',
    description: 'Add your signature to a PDF document',
    route: '/sign-pdf',
    icon: '✍️',
    color: '#6366f1',
    category: 'security',
    component: lazy(() => import('../tools/SignPdf/SignPdf')),
  },
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Add password protection to your PDF',
    route: '/protect-pdf',
    icon: '🔒',
    color: '#dc2626',
    category: 'security',
    component: lazy(() => import('../tools/ProtectPdf/ProtectPdf')),
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove password protection from a PDF',
    route: '/unlock-pdf',
    icon: '🔓',
    color: '#f59e0b',
    category: 'security',
    component: lazy(() => import('../tools/UnlockPdf/UnlockPdf')),
  },
  {
    id: 'annotate-pdf',
    name: 'Annotate PDF',
    description: 'Add highlights, notes, and annotations',
    route: '/annotate-pdf',
    icon: '📝',
    color: '#f43f5e',
    category: 'edit',
    component: lazy(() => import('../tools/AnnotatePdf/AnnotatePdf')),
  },
  {
    id: 'markdown-to-pdf',
    name: 'Markdown to PDF',
    description: 'Write Markdown and instantly export to a beautiful PDF',
    route: '/markdown-to-pdf',
    icon: '📝',
    color: '#8b5cf6',
    category: 'convert',
    component: lazy(() => import('../tools/MarkdownToPdf/MarkdownToPdf')),
    acceptTypes: ['.md', '.txt'],
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Word documents to PDF entirely in your browser',
    route: '/word-to-pdf',
    icon: '📄',
    color: '#2563eb',
    category: 'convert',
    component: lazy(() => import('../tools/WordToPdf/WordToPdf')),
    acceptTypes: ['.docx', '.doc'],
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert Spreadsheets into PDF reports locally',
    route: '/excel-to-pdf',
    icon: '📊',
    color: '#10b981',
    category: 'convert',
    component: lazy(() => import('../tools/ExcelToPdf/ExcelToPdf')),
    acceptTypes: ['.xlsx', '.xls', '.csv'],
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Safely extract text from PDF to Word (.docx)',
    route: '/pdf-to-word',
    icon: '📝',
    color: '#2563eb',
    category: 'convert',
    component: lazy(() => import('../tools/PdfToWord/PdfToWord')),
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Extract structured tables from PDF to Spreadsheet',
    route: '/pdf-to-excel',
    icon: '📊',
    color: '#10b981',
    category: 'convert',
    component: lazy(() => import('../tools/PdfToExcel/PdfToExcel')),
  },
];

export function getToolsByCategory(category: ToolCategory): ToolConfig[] {
  return toolRegistry.filter(tool => tool.category === category);
}

export function getToolById(id: string): ToolConfig | undefined {
  return toolRegistry.find(tool => tool.id === id);
}

export function getToolByRoute(route: string): ToolConfig | undefined {
  return toolRegistry.find(tool => tool.route === route);
}
